import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs-basics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row justify-center my-20 space-x-10">
          <Link href={`/`}>
            <h2>Home</h2>
          </Link>
          <Link href={`/products`}>
            <h2>Products</h2>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
